# -*- coding: utf-8 -*-
"""Testing_Drug_Potency

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEIbwXRZ3ZdFBVxpyIPTFdWg0zxMrVC3
"""

import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from matplotlib import pyplot as plt

df=pd.read_csv("/content/exp2_data.csv")

X = df.drop('pIC50', axis=1)
print(X)

"""**3.2. Output features**"""

Y = df.pIC50
Y.head()

"""**3.3. Examine the data dimension**"""

X.shape

Y.shape

"""**3.4. Remove low variance features**"""

from sklearn.feature_selection import VarianceThreshold
selection = VarianceThreshold(threshold=(.8 * (1 - .8)))
X = selection.fit_transform(X)
X.shape

"""4. Data split (80/20 ratio)"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
X_train.shape, Y_train.shape

X_test.shape, Y_test.shape

"""5. Building a Regression Model using Random Forest"""

model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, Y_train)
r2 = model.score(X_test, Y_test)
r2

Y_pred = model.predict(X_test)
Y_pred = pd.DataFrame(Y_pred, columns =['pIC50'])
Y_test = pd.DataFrame(Y_test, columns =['pIC50'])

"""6. Scatter Plot of Experimental vs Predicted pIC50 Values"""

plt.scatter(Y_test.pIC50, Y_pred.pIC50)
plt.xlabel("Experimental pIC50", fontsize='large', fontweight='bold')
plt.ylabel("Predicted pIC50", fontsize='large', fontweight='bold')
plt.show()